$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: anomaly-detection-with-automl-job-v35
description: Pipeline using AutoML classification task

experiment_name: anomaly-detection-experiment-v3

inputs:
  classification_base_data:
    type: uri_file
    path: ./base-mltable-folder/creditcard.csv

settings:
  default_compute: azureml:psefton-compute-cluster

jobs:
  loading_node:
    type: command
    properties:
      title: load-data
    component: file:./components/component_loading.yaml
    inputs:
      base_data: ${{parent.inputs.classification_base_data}}
    outputs:
      train_data:
        type: uri_folder
      test_data:
        type: uri_folder
      validation_data:
        type: uri_folder
  preprocessing_node:
    type: command
    component: file:./components/component_preprocessing.yaml
    inputs:
      train_data: ${{parent.jobs.loading_node.outputs.train_data}}
      validation_data: ${{parent.jobs.loading_node.outputs.validation_data}}
    outputs:
      preprocessed_train_data:
        type: mltable
      preprocessed_validation_data:
        type: mltable
  classification_node:
    type: automl
    task: classification
    primary_metric: accuracy
    limits:
      max_trials: 1
      max_concurrent_trials: 1
    target_column_name: "Class"
    training_data: ${{parent.jobs.preprocessing_node.outputs.preprocessed_train_data}}
    validation_data: ${{parent.jobs.preprocessing_node.outputs.preprocessed_validation_data}}
    featurization:
      mode: "auto"
    training:
      enable_stack_ensemble: false
      enable_vote_ensemble: false
    outputs:
       best_model:
          type: mlflow_model
  register_model_node:
    type: command
    component: file:./components/component_register_model.yaml
    inputs:
      model_input_path: ${{parent.jobs.classification_node.outputs.best_model}}
      model_base_name: credit_card_fraud_detection_model